/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CostRouteImport } from './routes/cost'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsCommandsRouteImport } from './routes/docs/commands'
import { Route as DocsConfigurationRouteImport } from './routes/docs/configuration'
import { Route as DocsInstallRouteImport } from './routes/docs/install'
import { Route as DocsLocalModelsRouteImport } from './routes/docs/local-models'
import { Route as DocsMcpRouteImport } from './routes/docs/mcp'
import { Route as DocsModelsRouteImport } from './routes/docs/models'
import { Route as DocsModesRouteImport } from './routes/docs/modes'
import { Route as DocsSubagentsRouteImport } from './routes/docs/subagents'
import { Route as DocsTmuxRouteImport } from './routes/docs/tmux'
import { Route as DocsWisprFlowRouteImport } from './routes/docs/wispr-flow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCommandsRoute = DocsCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallRoute = DocsInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLocalModelsRoute = DocsLocalModelsRouteImport.update({
  id: '/local-models',
  path: '/local-models',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => DocsRoute,
} as any)
const DocsModelsRoute = DocsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DocsRoute,
} as any)
const DocsModesRoute = DocsModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSubagentsRoute = DocsSubagentsRouteImport.update({
  id: '/subagents',
  path: '/subagents',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTmuxRoute = DocsTmuxRouteImport.update({
  id: '/tmux',
  path: '/tmux',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWisprFlowRoute = DocsWisprFlowRouteImport.update({
  id: '/wispr-flow',
  path: '/wispr-flow',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cost': typeof CostRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/local-models': typeof DocsLocalModelsRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/models': typeof DocsModelsRoute
  '/docs/modes': typeof DocsModesRoute
  '/docs/subagents': typeof DocsSubagentsRoute
  '/docs/tmux': typeof DocsTmuxRoute
  '/docs/wispr-flow': typeof DocsWisprFlowRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cost': typeof CostRoute
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/local-models': typeof DocsLocalModelsRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/models': typeof DocsModelsRoute
  '/docs/modes': typeof DocsModesRoute
  '/docs/subagents': typeof DocsSubagentsRoute
  '/docs/tmux': typeof DocsTmuxRoute
  '/docs/wispr-flow': typeof DocsWisprFlowRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cost': typeof CostRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/commands': typeof DocsCommandsRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/local-models': typeof DocsLocalModelsRoute
  '/docs/mcp': typeof DocsMcpRoute
  '/docs/models': typeof DocsModelsRoute
  '/docs/modes': typeof DocsModesRoute
  '/docs/subagents': typeof DocsSubagentsRoute
  '/docs/tmux': typeof DocsTmuxRoute
  '/docs/wispr-flow': typeof DocsWisprFlowRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cost'
    | '/docs'
    | '/docs/commands'
    | '/docs/configuration'
    | '/docs/install'
    | '/docs/local-models'
    | '/docs/mcp'
    | '/docs/models'
    | '/docs/modes'
    | '/docs/subagents'
    | '/docs/tmux'
    | '/docs/wispr-flow'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cost'
    | '/docs/commands'
    | '/docs/configuration'
    | '/docs/install'
    | '/docs/local-models'
    | '/docs/mcp'
    | '/docs/models'
    | '/docs/modes'
    | '/docs/subagents'
    | '/docs/tmux'
    | '/docs/wispr-flow'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/cost'
    | '/docs'
    | '/docs/commands'
    | '/docs/configuration'
    | '/docs/install'
    | '/docs/local-models'
    | '/docs/mcp'
    | '/docs/models'
    | '/docs/modes'
    | '/docs/subagents'
    | '/docs/tmux'
    | '/docs/wispr-flow'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostRoute: typeof CostRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/commands': {
      id: '/docs/commands'
      path: '/commands'
      fullPath: '/docs/commands'
      preLoaderRoute: typeof DocsCommandsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/install': {
      id: '/docs/install'
      path: '/install'
      fullPath: '/docs/install'
      preLoaderRoute: typeof DocsInstallRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/local-models': {
      id: '/docs/local-models'
      path: '/local-models'
      fullPath: '/docs/local-models'
      preLoaderRoute: typeof DocsLocalModelsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/mcp': {
      id: '/docs/mcp'
      path: '/mcp'
      fullPath: '/docs/mcp'
      preLoaderRoute: typeof DocsMcpRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/models': {
      id: '/docs/models'
      path: '/models'
      fullPath: '/docs/models'
      preLoaderRoute: typeof DocsModelsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/modes': {
      id: '/docs/modes'
      path: '/modes'
      fullPath: '/docs/modes'
      preLoaderRoute: typeof DocsModesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/subagents': {
      id: '/docs/subagents'
      path: '/subagents'
      fullPath: '/docs/subagents'
      preLoaderRoute: typeof DocsSubagentsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tmux': {
      id: '/docs/tmux'
      path: '/tmux'
      fullPath: '/docs/tmux'
      preLoaderRoute: typeof DocsTmuxRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/wispr-flow': {
      id: '/docs/wispr-flow'
      path: '/wispr-flow'
      fullPath: '/docs/wispr-flow'
      preLoaderRoute: typeof DocsWisprFlowRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsCommandsRoute: typeof DocsCommandsRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsInstallRoute: typeof DocsInstallRoute
  DocsLocalModelsRoute: typeof DocsLocalModelsRoute
  DocsMcpRoute: typeof DocsMcpRoute
  DocsModelsRoute: typeof DocsModelsRoute
  DocsModesRoute: typeof DocsModesRoute
  DocsSubagentsRoute: typeof DocsSubagentsRoute
  DocsTmuxRoute: typeof DocsTmuxRoute
  DocsWisprFlowRoute: typeof DocsWisprFlowRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCommandsRoute: DocsCommandsRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsInstallRoute: DocsInstallRoute,
  DocsLocalModelsRoute: DocsLocalModelsRoute,
  DocsMcpRoute: DocsMcpRoute,
  DocsModelsRoute: DocsModelsRoute,
  DocsModesRoute: DocsModesRoute,
  DocsSubagentsRoute: DocsSubagentsRoute,
  DocsTmuxRoute: DocsTmuxRoute,
  DocsWisprFlowRoute: DocsWisprFlowRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostRoute: CostRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
